import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Atlantis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-bt">
      <body>
        <Header />
        <div className="flex flex-col px-32 py-12 w-full gap-6">
        {children}
        </div>
      </body>
    </html>
  );
}